// ไฟล์: GlobalUsings.cs
global using System.Collections;
global using System.Collections.Generic;
global using UnityEngine;
global using BombGame.EnumSpace;
global using BombGame.RecordEventSpace;
global using BombGame.Ability;
global using BombGame.Data;
global using BombGame.StateSpace;
global using BombGame.StrategySpace;